[package]
name = "a_new_os"
version = "0.1.0"
authors = ["dvedvick@gmail.com"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.3.4"

[package.metadata.bootimage]
default-target = "x86_64-new-os.json"
